### ISSUE TITLE
The samtools and bcftools version used for calling SNP in the SWEEP_GOLD pipeline?

### ISSUE THREAD

**Issue by zhangleisdau** [w-korani/SWEEP_GOLD#1]
Dear Korani:
        The manual showed that the program takes vcf file as input, but it did not specify which version of the samtools and bcftools were used to call SNPs? Could you please list the command examples of how to use samtools and bcftools? 
        Thank you very much, looking forword to your reply!
        Best!
                                                                                                                                                            lei zhang

**Comment by jclev-uga** [comment]
For sweep-gold it does not matter how the vcf file  is generated because the program only considers the potential SNP positions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by w-korani** [comment]
Yes, you can use any vcf version, The program only uses SNP coordinates (the first two columns) from the vcf file. Afterwards, all processes run on bam files. Eventually, the vcf file is used again, just to filter SNPs using the same coordinates.
