### ISSUE TITLE
The meaning of MAF and DEP?

### ISSUE THREAD

**Issue by zhangleisdau** [w-korani/SWEEP_GOLD#2]
Dear Korani:
         I used sweep_gold with the default parameters to call SNPs from the sweetpotato(hexaploid genome, 88 genotypes); finally, only 16 SNPs were got in the final vcf files. But when i set "maf = 0", 14757 SNPs were got. I want to know what the maf (**the number of samples or the number alleles** that posses second most common allele) and DEP (minimum depth to accept a haplotype in every sample) means?  Could you please show me algorithms of SWEEP_GOLD ?
         Thank you very much, looking forword to your reply!
Best!
lei zhang

**Comment by w-korani** [comment]
Dear Zhangleisdau,
Please check this graph/paper:
https://www.frontiersin.org/files/Articles/357113/fpls-09-00564-HTML/image_m/fpls-09-00564-g001.jpg
In the graph, there are 4 and 5 sequences, which covered the two SNPs and passed the explained filter. So if you assign DEP to 4, this SNP should be called. However, if you assigned it to 5 or more, this SNP will not be called as the **minimum depth to accept a haplotype**, should be for all genotypes. 

Regarding MAF, the graph shows two genotypes, which passed the criteria (explained in the graph). MAF represents number of the genotype pairs passed the criteria relative to the population size. For example, if you have 200 genotypes in the population, and you set MAF to 5. (5/200)*100 = 2.5, rounded up to 3. So at least 3 consecutive genotype pairs should pass the criteria for the minimum provided DEP to call this SNP.

Regarding to the sweetpotato dataset, when you set MAF to default 5. (5/88)*100 = 5.6 ~ 6 genotype pairs should pass the MAF criteria at the provided DEP, default is 5. This is tough to occur for sweetpotato, which is highly heterozygous. Therefore, low number locations/genotypes will have the scaffold (the second location in the graph)
when you set MAF to 0, only SNPs that have the DEP cutoff were called without implementing the criteria of MAF (explained in the graph).
I suggest you to reduce MAF and DEP to 1, I think this is reasonable for sweetpotato especially if you do not have high depth coverage. 

Regards,
Walid
